export default {
    OrderIndex:{
        url:'project/order/index',
        method:"POST"
    },
    OrderAdd:{
        url:'project/order/add',
        method:"POST"
    },
    OrderPay:{
        url:'project/order/pay',
        method:"POST"
    },
    OrderInfo:{
        url:'project/order/info',
        method:"POST"
    },
    OrderRevoke:{
        url:'project/order/revoke',
        method:"POST"
    },
    Cancel:{
        url:'project/order/cancel',
        method:"POST"
    },
    Rate:{
        url:'project/order/rate',
        method:"POST"
    },
    Del:{
        url:'project/order/del',
        method:"POST"
    }
}